# Generated by Django 5.0.4 on 2024-04-20 05:16

import portifolya.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, validators=[portifolya.models.validate_url], verbose_name='Facebook manzilingizni keriting')),
                ('telegram', models.CharField(blank=True, max_length=200, null=True, validators=[portifolya.models.validate_url], verbose_name='Telegram manzilingizni keriting')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, validators=[portifolya.models.validate_url], verbose_name='Instagram manzilingizni keriting')),
            ],
        ),
    ]
