# Generated by Django 5.0.4 on 2024-04-21 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0002_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='manzilni kiriting: ')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="To'g'ri telefon raqamini kiriting.", regex='^\\+?998\\d{9}$')], verbose_name='Telefon raqamingizni keriting')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email manzilingizni kiriting')),
            ],
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Manzil keritildi', 'verbose_name_plural': 'Manzillari keritildi'},
        ),
    ]
