# Generated by Django 5.0.4 on 2024-04-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0005_contact_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.BigIntegerField(blank=True, null=True)),
                ('projects', models.BigIntegerField(blank=True, null=True)),
                ('customers', models.BigIntegerField(blank=True, null=True)),
                ('coffee', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
