# Generated by Django 5.0.4 on 2024-04-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0006_follower_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoshop', models.PositiveIntegerField(blank=True, null=True, verbose_name='100 foizdan necha foiz bilishingizni yozing')),
                ('html5', models.PositiveIntegerField(blank=True, null=True, verbose_name='100 foizdan necha foiz bilishingizni yozing')),
                ('wordpress', models.PositiveIntegerField(blank=True, null=True, verbose_name='100 foizdan necha foiz bilishingizni yozing')),
                ('jquery', models.PositiveIntegerField(blank=True, null=True, verbose_name='100 foizdan necha foiz bilishingizni yozing')),
                ('css', models.PositiveIntegerField(blank=True, null=True, verbose_name='100 foizdan necha foiz bilishingizni yozing')),
                ('seo', models.PositiveIntegerField(blank=True, null=True, verbose_name='100 foizdan necha foiz bilishingizni yozing')),
            ],
        ),
    ]
