# Generated by Django 5.0.4 on 2024-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0007_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='css',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='html5',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='jquery',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='photoshop',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='seo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='wordpress',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
