# Generated by Django 5.0.4 on 2024-04-23 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0008_alter_skill_css_alter_skill_html5_alter_skill_jquery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['skill_name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='css',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='html5',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='jquery',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='photoshop',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='seo',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='wordpress',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_foiz',
            field=models.PositiveSmallIntegerField(default=None, verbose_name=[django.core.validators.MinValueValidator(1, message="Skill's foiz must be between 1 and 100"), django.core.validators.MaxValueValidator(100, message="Skill's foiz must be between 1 and 100")]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default=None, max_length=120, unique=True, verbose_name='Skill'),
            preserve_default=False,
        ),
    ]
