# Generated by Django 5.0.4 on 2024-04-23 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0009_alter_skill_options_remove_skill_css_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_foiz',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='1 dan katta kiriting'), django.core.validators.MaxValueValidator(100, message='100 dan kichik kiriting')]),
        ),
    ]
