# Generated by Django 5.0.4 on 2024-04-23 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0010_alter_skill_skill_foiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='link',
            new_name='About',
        ),
    ]
