# Generated by Django 5.0.4 on 2024-04-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0011_rename_link_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='email',
            field=models.EmailField(default=None, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='phone_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
