# Generated by Django 5.0.4 on 2024-04-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0012_alter_service_email_alter_service_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service',
        ),
    ]
