# Generated by Django 5.0.4 on 2024-04-25 04:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0013_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='Email manzilingizni kiriting'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Manzilingizni kiriting: '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="To'g'ri telefon raqamini kiriting.", regex='^\\+?998\\d{9}$')], verbose_name='Telefon raqamingizni keriting'),
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_email', to='portifolya.contact', to_field='email')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_location', to='portifolya.contact', to_field='location')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_phone_number', to='portifolya.contact', to_field='phone_number')),
            ],
        ),
    ]
