# Generated by Django 5.0.4 on 2024-04-25 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0014_alter_contact_email_alter_contact_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_phone_number', to='portifolya.contact', to_field='phone_number'),
        ),
    ]
