# Generated by Django 5.0.4 on 2024-04-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0016_alter_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='phone_number',
        ),
    ]
