# Generated by Django 5.0.4 on 2024-04-25 04:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0017_remove_service_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='phone_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_phone_number', to='portifolya.contact', to_field='phone_number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="To'g'ri telefon raqamini kiriting.", regex='^\\+?998\\d{9}$')], verbose_name='Telefon raqamingizni keriting'),
        ),
    ]
