# Generated by Django 5.0.4 on 2024-04-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0018_service_phone_number_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'Abouts'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('location', 'email', 'website'), 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('location', 'email', 'phone_number'), 'verbose_name_plural': 'Services'},
        ),
    ]
