# Generated by Django 5.0.4 on 2024-04-25 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0019_alter_about_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='email',
        ),
        migrations.RemoveField(
            model_name='service',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portifolya.contact'),
        ),
    ]
