# Generated by Django 5.0.4 on 2024-04-26 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0021_alter_service_options_service_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name="To'liq ismingizni kiriting : ")),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manzilni kiriting : ')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='Email manzilingizni kiriting')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="To'g'ri telefon raqamini kiriting.", regex='^\\+?998\\d{9}$')], verbose_name='Telefon raqamingizni keriting')),
            ],
        ),
    ]
