# Generated by Django 5.0.4 on 2024-04-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0022_me'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Me',
            new_name='About_Me',
        ),
    ]
