# Generated by Django 5.0.4 on 2024-04-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0023_rename_me_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.CharField(max_length=10, unique=True, verbose_name='yilni kiriting masalan(2014-2015)')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='sarlavhani kiriting')),
                ('where', models.CharField(max_length=30, unique=True, verbose_name='Qayerdaligini kiriting')),
                ('description', models.TextField(max_length=500, verbose_name='Izoh yozing')),
            ],
        ),
    ]
