# Generated by Django 5.0.4 on 2024-04-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolya', '0024_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Izoh yozing'),
        ),
    ]
